apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: pythonapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pythonapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: pythonapp
    spec:
      containers:
      - image: depuis2031/python-app:15
        name: pythonapp
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: pythonappsvc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 5000
  selector:
    app: pythonapp
